dataset: "testonly"
network: "imagenet_ll_ensemble"
method: "ensemble"
# WANDB_RNAME assumed to be set
env:
  MODEL_DIR: "pretrained_models"
  EXPERIMENT_DUMP: "experiment_runs"
  EXPERIMENT_NAME: "baseline_ensemble_ll_imagenet"
  DS_BS: 1024
  RUN_ON_SUBSAMPLE: "0:1024"
save_to:
  path: ${BASE_WORKDIR}/experiment_runs/${EXPERIMENT_NAME}/${RNG_SEED}/${RUN_ON_DATASET}/
  prefix:
  items:
    preds.pkl:
      - average_net_pred
      - sample_preds
      - target
