dataset: "imagenet_encoded"
network: "imagenet_ll"
method: "mcdo_hparams"
# WANDB_RNAME assumed to be set
env:
  MODEL_DIR: "pretrained_models"
  EXPERIMENT_DUMP: "experiment_runs"
save_to:
  path: ${BASE_WORKDIR}/experiment_runs/${USE_METHOD_CONF}_${ID_DATA}_${OOD_DATA}/${RUN_ON_DATASET}/
  prefix: ''
  items:
    preds.pkl:
      - average_net_pred
      - sample_preds
      - target
