dataset: "testonly"
#network: "imagenet_ll_stock"
network: "efficientnet_golden_dragon_ensemble"
method: "ensemble"
env:
  MODEL_DIR: "pretrained_models"
  EXPERIMENT_DUMP: "experiment_runs"
  DS_BS: 100
  #USE_BFLOAT: true
save_to:
  path: ${PUBWORK}/experiment_runs/imagenet_full_ensemble_rerun/${RNG_SEED}/${RUN_ON_DATASET}/
  prefix: ${RUN_PREFIX|}
  items:
    preds.npy:
      - average_net_pred
      - sample_preds
    aux.pkl:
      - target
      - obj_loss
      - train_loss
      - pen_loss
      - model_train_loss

