env:
  EXPERIMENT_NAME: "ood"
  MODEL_DIR: "pretrained_models"
  CUDA_DEVICE: "cuda:0"
  ID_DATA: "imagenet-projected"
  OOD_DATA: "imagenet-a-projected"
load_samples:
  id_uncerts:
    config: ${USE_METHOD_CONF}
    env:
      RUN_ON_DATASET: ${ID_DATA}
      DS_SUBSET: test
  ood_uncerts:
    config: ${USE_METHOD_CONF}
    env:
      RUN_ON_DATASET: ${OOD_DATA}
      DS_SUBSET: test
samples2uncerts:
  uncertainty_our:
    filter:
#       name: all
# enable for non-tempered version
      name: best
      gamma_slack: ${OPT_GAMMA|1.e-2}
      window_size: ${EMA_WINDOW|5}
    unc_params: {}
experiment_evaluation:
  ood: {}
save_to:
  path: ${BASE_WORKDIR}/experiment_runs/${WANDB_SWEEPNAME}_${EXPERIMENT_NAME}_${ID_DATA}_${OOD_DATA}/${WANDB_RNAME}
