name: quam
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=1.12.1
  - cudatoolkit=11.6
  - pandas
  - numpy
  - scipy
  - tqdm
  - matplotlib
  - seaborn
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - jupyterlab
  - scikit-learn
  - gitpython
  - pip
  - pip:
      - wandb
      - wget
      - laplace-torch
      - git+https://github.com/AdamCobb/hamiltorch
      - torch-sgld
      - GitPython
