net_id: "mnist_lenet"
device: ${CUDA_DEVICE|cuda:0}
net_properties:
  p_dropout: ${P_DROPOUT|0.2}
  out_features: 10
  mnist: true
  checkpoint: "${BASE_WORKDIR}/${MODEL_DIR}/LeNet_MNIST/seed_${RNG_SEED}/model_0.pt"
